FROM python:3.11
WORKDIR /app
RUN pip install --upgrade pip
COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY . /app/
RUN python manage.py collectstatic --noinput
EXPOSE 8000
COPY start_celery.sh /app/start_celery.sh
RUN chmod +x /app/start_celery.sh
CMD ["/app/start_celery.sh"]