FROM python:3.11

# Set working directory
WORKDIR /app

# Install dependencies
RUN pip install --upgrade pip
COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY . /app/
RUN python manage.py collectstatic --noinput
EXPOSE 8000
COPY celeryentrypoint.sh /app/celeryentrypoint.sh
RUN chmod +x /app/celeryentrypoint.sh
ENTRYPOINT ["/app/celeryentrypoint.sh"]