app = "myshop" 
primary_region = "fra"  

[env]
DJANGO_SETTINGS_MODULE = "myshop.settings"

[build]
  image = "sergeyitaly/koloryt:serhii_celery" 

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true
  memory = "1Gi" 
  
[services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20
