app = "myshop"
primary_region = "fra"

[env]
DJANGO_SETTINGS_MODULE = "myshop.settings"

[build]
  image = "sergeyitaly/koloryt:serhii_celery"

[[services]]
  internal_port = 8000 
  external_port = 80    # Expose it to the internet
  force_https = true

[[services]]
  internal_port = 5555  # Celery worker port
  external_port = 80
  protocol = "tcp"

[services]
memory = "2GB" 