[app]
name = "myshop"
count = 1  # Ensure only one machine
primary_region = "ord"

[build]
image = "sergeyitaly/koloryt:serhii_celery"

[env]
DJANGO_SETTINGS_MODULE = "myshop.settings"

[processes]
app = "gunicorn myshop.wsgi:application --workers=1 --worker-class=gevent"
worker = "celery -A myshop worker --loglevel=info --pool=gevent --concurrency=1"
beat = "celery -A myshop beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"

[[services]]
internal_port = 8000
processes = [ "app", "worker", "beat" ]
protocol = "tcp"

  [services.concurrency]
  hard_limit = 4
  soft_limit = 3
  type = "connections"

  [[services.ports]]
  force_https = true
  handlers = [ "http" ]
  port = 80
