app = "myshop" 
primary_region = "fra"  

[env]
DJANGO_SETTINGS_MODULE = "myshop.settings"

[build]
  image = "sergeyitaly/koloryt:serhii_celery" 

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
[resources]
memory = 4096