app = "myshop" 
primary_region = "fra"  

[env]
DJANGO_SETTINGS_MODULE = "myshop.settings"

[build]
  image = "sergeyitaly/koloryt:serhii_celery" 

[[services]]
  internal_port = 8000
  protocol = "tcp"
  [services.ports]
    http = 80
    https = 443

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25
    grace_period = "10s"
