# Generated by Django 3.2.12 on 2024-04-14 08:55

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20240411_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=shop.models.MediaStorage(), upload_to='photos/collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brandimage',
            field=models.FileField(blank=True, null=True, storage=shop.models.MediaStorage(), upload_to='photos/svg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=shop.models.MediaStorage(), upload_to='photos/product'),
        ),
    ]
