# Generated by Django 3.2.12 on 2024-04-20 07:44

from django.db import migrations
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20240419_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brandimage',
        ),
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=shop.models.FlexibleImageField(blank=True, null=True, storage=shop.models.MediaStorage(), upload_to='photos/collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=shop.models.FlexibleImageField(blank=True, null=True, storage=shop.models.MediaStorage(), upload_to='photos/product'),
        ),
    ]
