# Generated by Django 3.2.12 on 2024-04-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='currency',
            field=models.CharField(choices=[('UAH', 'UAH (грн)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)')], default='UAH', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('UAH', 'UAH (грн)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)')], default='UAH', max_length=3),
        ),
    ]
