# Generated by Django 3.2.12 on 2024-04-20 09:14

from django.db import migrations
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20240420_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=shop.models.FlexibleImageField(upload_to='photos/collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=shop.models.FlexibleImageField(default=2, upload_to='photos/product'),
            preserve_default=False,
        ),
    ]
