# Generated by Django 3.2.12 on 2024-04-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20240420_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('name',), 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
    ]
