# Generated by Django 3.2.12 on 2024-04-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20240420_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.ImageField(default=2, upload_to='photos/collection'),
            preserve_default=False,
        ),
    ]
