# Generated by Django 3.2.12 on 2024-04-14 20:25

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20240414_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=shop.models.MediaStorage(), upload_to='photos/collection'),
        ),
    ]
