# Generated by Django 3.2.12 on 2024-04-20 21:13

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20240421_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/collection', validators=[shop.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='brandimage',
            field=models.FileField(blank=True, null=True, upload_to='photos/svg', validators=[shop.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/product', validators=[shop.models.validate_file_extension]),
        ),
    ]
