/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
import { createFileRoute } from '@tanstack/react-router';
// Import Routes
import { Route as rootRoute } from './routes/__root';
// Create Virtual Routes
const AboutLazyImport = createFileRoute('/about')();
const IndexLazyImport = createFileRoute('/')();
// Create/Update Routes
const AboutLazyRoute = AboutLazyImport.update({
    path: '/about',
    getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/about.lazy').then((d) => d.Route));
const IndexLazyRoute = IndexLazyImport.update({
    path: '/',
    getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/index.lazy').then((d) => d.Route));
// Create and export the route tree
export const routeTree = rootRoute.addChildren([IndexLazyRoute, AboutLazyRoute]);
/* prettier-ignore-end */
