name = "koloryt-notifications"
type = "typescript"

# Use a boolean value for workers_dev
workers_dev = true

# Specify the main entry point for your Worker script
main = "dist/worker.js"

# Define compatibility date for the Worker
compatibility_date = "2024-07-25"

# Define environment-specific configurations
[env.production]
name = "koloryt-notifications-production"
workers_dev = false  # Disable workers_dev for production environment

# Define environment-specific variables
[env.production.vars]
VERCEL_DOMAIN='https://myshop-topaz-five.vercel.app'
NOTIFICATIONS_API='6903287850:AAHtZPQgaK7kIKrHOHIbXMK-SanidRxyfas'
SECRET_TOKEN='wefrevervgpkpmwofmr4obguy5d'
