platform :android do
  desc "Build Android App Bundle"
  lane :build do
    gradle(
      task: "clean bundleRelease"
    )
  end

  desc "Deploy APK/AAB to Google Play Store"
  lane :deploy do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store(
      json_key: "../../koloryt-project-658aa790b0ef.json",
      track: "production", # Change to 'beta' or 'production' as per your track
      package_name: "com.koloryt"
    )
  end
end
